# Generated by Django 3.0.5 on 2020-04-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200421_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiclesbranch', to='api.Branch'),
        ),
    ]
